version: '2.1'

services:
  typescript-apollo-boilerplate:
    image: typescript-apollo-boilerplate
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
	  